[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "libb"
version = "0.0.0"
description = "Research framework for persistent portfolio analytics"
requires-python = ">=3.10"
