[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "libb"
version = "0.2.8"
description = "LLM Research framework for persistent portfolio analytics"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["libb*"]
